app:
    resource: '@AppBundle/Controller'
    type: annotation

main_route:
    path: /
    defaults: {_controller: 'AppBundle:Default:index'}

#FOSUserBundle
fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"